# To build the image
# Tool can be found at
# https://github.com/lord63/choosealicense-cli
#
#    docker build \
#        -t abxsantos/choosealicensecli:latest \
#        -f Dockerfile.chosealicensecli .

FROM python:3.8-alpine

LABEL maintainer "Alexandre Xavier <ale.bxsantos@gmail.com>"

RUN set -x \
    && apk add --no-cache bash git openssh \
    && git --version && bash --version && ssh -V

RUN pip install -U choosealicense-cli

WORKDIR /workspace
