# To build the image
# Tool can be found at
# https://github.com/ggreer/the_silver_searcher
#
#    docker build \
#        -t abxsantos/ag:latest \
#        -f Dockerfile.ag .


FROM alpine:latest

MAINTAINER "Alexandre Xavier <ale.bxsantos@gmail.com>"

RUN apk --update add the_silver_searcher

WORKDIR /tmp

ENTRYPOINT ["ag"]

CMD ["--help"]
