FROM python:alpine

MAINTAINER "Alexandre Xavier <ale.bxsantos@gmail.com>"

# Installs dependencies
RUN set -eux && apk add --no-cache bc gcc musl-dev

RUN pip install mypy


ARG USER_ID=1000

# Creates a non-root user
RUN adduser --disabled-password --gecos '' --uid ${USER_ID} docker

# Applies the container user to be non-root
USER docker

WORKDIR /home/docker

ENTRYPOINT ["mypy"]