FROM python:alpine

MAINTAINER "Alexandre Xavier <ale.bxsantos@gmail.com>"

# Install latest flake8
RUN pip install pydocstyle


ARG USER_ID=1000

# Creates a non-root user
RUN adduser --disabled-password --gecos '' --uid ${USER_ID} docker

# Applies the container user to be non-root
USER docker

WORKDIR /home/docker

ENTRYPOINT ["pydocstyle"]