FROM python:alpine

MAINTAINER "Alexandre Xavier <ale.bxsantos@gmail.com>"

# Install latest autoflake
RUN pip install autoflake

# Creates a non-root user
RUN adduser --disabled-password docker

# Applies the container user to be non-root
USER docker

WORKDIR /home/docker

ENTRYPOINT ["autoflake"]